[workspace]
members = [
    "rfw",
    "examples/animated-wgpu",
    # "examples/animated-metal",
    "examples/d2",
    "examples/nphysics",
    "backends/wgpu",
    # "backends/gfx",
    # "backends/metal",
    # "backends/rendy",
    "crates/rfw-backend",
    "crates/rfw-ecs",
    "crates/rfw-font",
    "crates/rfw-graph",
    "crates/rfw-math",
    "crates/rfw-scene",
    "crates/rfw-utils"
]

[profile.release]
debug = true

[profile.dev.package."*"]
opt-level = 1