[workspace]
members = [
    "rfw",
    "examples/animated",
    # "examples/d2",
    # "examples/nphysics",
    # "examples/simple",
    "backends/wgpu",
    "backends/gfx",
#    "backends/rendy",
    "crates/rfw-backend",
    "crates/rfw-scene",
    "crates/rfw-math",
    "crates/rfw-utils",
    "crates/rfw-font",
    #"renderers/gpu-rt",
]

[profile.dev.package."*"]
opt-level = 1
