[package]
name = "rust-raytracer"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-fb-template = { git = "https://github.com/MeirBon/cpu-fb-template.git" }