[workspace]
members = [
    "examples/animated",
    "examples/physics",
    "examples/simple",
    "renderers/cpu-rt",
    "renderers/deferred",
    "renderers/gpu-rt",
    "renderers/shared",
    "scene"
]

[profile.release]
debug = 2