[package]
name = "rust-raytracer"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

[dependencies]
bvh = { path = "bvh" }
fb-template = { path = "fb-template" }
rayon = "1.3.0"
num_cpus = "1.12.0"
glam = "0.8.6"
rand = "0.7.3"
tobj = "0.1.12"
num = "0.2.1"
crossbeam = "0.7.3"