[package]
name = "rust-raytracer"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

[features]
multithreading = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-fb-template = { git = "https://github.com/MeirBon/cpu-fb-template.git" }
rayon = "1.3.0"
crossbeam = "0.7.3"
num_cpus = "1.12.0"
glam = "0.8.6"
rand = "0.7.3"
tobj = "0.1.12"
