[workspace]
members = [
    "rfw",
    "examples/animated",
    "examples/d2",
    "examples/nphysics",
    "examples/simple",
    "backends/wgpu",
    "backends/gfx",
    #"renderers/gpu-rt",
]

[profile.dev.package."*"]
opt-level = 1
