[workspace]
members = [
    "renderers/cpu-rt",
    "renderers/deferred",
    "renderers/gpu-rt",
    "renderers/metal-rt",
    "renderers/shared",
    "renderers/vulkan",
    "scene"
]

[profile.dev]
opt-level = 2
debug = 2