[workspace]
members = [
    "examples/animated",
    "examples/nphysics",
    "examples/ray-cast",
    "examples/simple",
    "renderers/deferred",
    "renderers/gpu-rt",
    "renderers/shared",
    "renderers/vulkan",
    "renderers/gfx",
    "scene",
    "system",
    "utils",
]

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 2
