[package]
name = "fb-template"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

[dependencies]
winit = "0.21.0"
wgpu = "0.5.0"
shaderc = "0.6.2"
glam = "0.8.6"
imgui = "0.3"
imgui-wgpu = "0.6.0"
imgui-winit-support = "0.3.1"
futures = "0.3"