[package]
name = "rfw-system"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfw-scene = { path = "../scene" }
glam = "0.9.2"
futures = "0.3"