#ifndef VULKANRTCPP_BACKENDS_VULKAN_RT_CPP_SRC_VULKAN_LOADER_H
#define VULKANRTCPP_BACKENDS_VULKAN_RT_CPP_SRC_VULKAN_LOADER_H

#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1

#pragma warning(push, 0)
#include <vulkan/vulkan.hpp>
#pragma warning(pop)

#endif // VULKANRTCPP_BACKENDS_VULKAN_RT_CPP_SRC_VULKAN_LOADER_H
