#ifndef VULKANRTCPP_BACKENDS_VULKAN_RT_CPP_SRC_VULKAN_LOADER_H
#define VULKANRTCPP_BACKENDS_VULKAN_RT_CPP_SRC_VULKAN_LOADER_H

//#define VULKAN_HPP_STORAGE_SHARED/
//#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1

#include <vulkan/vulkan.hpp>

#endif // VULKANRTCPP_BACKENDS_VULKAN_RT_CPP_SRC_VULKAN_LOADER_H
