[package]
name = "rfw-utils"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
threadpool = "1.8.1"
futures = "0.3"
futures-executor = { version = "0.3", features = ["thread-pool"] }
num_cpus = "1.13.0"
