[package]
name = "d2"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

[dependencies]
winit = "0.25"
futures = "0.3"
rfw = { path = "../../rfw" }
rfw-font = { path = "../../crates/rfw-font" }
rfw-backend-wgpu = { path = "../../backends/wgpu" }
