[package]
name = "animated"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22"
glam = "0.8"
futures = "0.3"
clap = "2.33.1"
glyph_brush = "0.7.0"
rayon = "1.4.0"
rfw-system = { path = "../../system" }
rfw-deferred = { path = "../../renderers/deferred" }
rfw-gfx = { path = "../../renderers/gfx" }
rfw-gpu-rt = { path = "../../renderers/gpu-rt" }
shared = { path = "../../renderers/shared" }
