[package]
name = "rfw-backend-wgpu"
version = "0.1.0"
authors = ["meir"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
wgpu = "0.6"
futures = "0.3"
rfw = { path = "../../rfw" }
bitvec = "0.19"

[build-dependencies]
rfw = { path = "../../rfw" }
