[package]
name = "rfw-backend-wgpu"
version = "0.1.0"
authors = ["meir"]
edition = "2018"
build = "build.rs"
description = "A wgpu-based backend for rfw."
license = "Apache-2.0"

[dependencies]
num_cpus = "1.13"
wgpu = "0.6"
futures = "0.3"
rfw = "0.1"
bitvec = "0.19"

[build-dependencies]
rfw = "0.1"
